"use client"

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { useMemo } from "react"
import { createClient } from "@/lib/supabase/client"
import { queryKeys } from "@/lib/query-keys"
import type { Insight } from "@/lib/types"

// ── Mapper ────────────────────────────────────────────────────────────────────

function mapInsight(i: any): Insight {
  return {
    id:       i.id,
    type:     i.type,
    priority: i.priority as Insight["priority"],
    message:  i.message,
    date:     i.created_at.split("T")[0],
  }
}

// ── Hook ─────────────────────────────────────────────────────────────────────

/**
 * Returns insights list + addInsight helper.
 * Uses Supabase directly — insights are generated by Supabase Edge Functions
 * and are not migrated to the Python API (DEC-15).
 */
export function useInsights() {
  const queryClient = useQueryClient()
  const supabase    = useMemo(() => createClient(), [])

  const query = useQuery({
    queryKey: queryKeys.insights.all(),
    queryFn: async (): Promise<Insight[]> => {
      const { data, error } = await supabase
        .from("ai_insights")
        .select("*")
        .order("created_at", { ascending: false })

      if (error) throw error
      return (data ?? []).map(mapInsight)
    },
    staleTime: 5 * 60 * 1000, // 5 min — insights change only after AI generation
  })

  /**
   * Optimistically prepend an insight to the cache (used after AI generation,
   * before the list is refetched). Mirrors the old DataContext `addInsight(i)`.
   */
  function addInsight(insight: Insight): void {
    queryClient.setQueryData<Insight[]>(queryKeys.insights.all(), old =>
      [insight, ...(old ?? [])]
    )
  }

  /**
   * Invalidate and refetch insights (e.g. after generating new ones).
   */
  async function refreshInsights(): Promise<void> {
    await queryClient.invalidateQueries({ queryKey: queryKeys.insights.all() })
  }

  return {
    insights:        query.data ?? [],
    isLoading:       query.isLoading,
    isError:         query.isError,
    error:           query.error,
    addInsight,
    refreshInsights,
  }
}
