// Regresión del remito de VENTA tanda B (convertir en venta por la UI, borrar la venta que nació del remito) tras los helpers por sentido.
import { readFileSync } from 'node:fs'
import { chromium, BASE, newCtx, login as uiLogin } from './pw-lib.mjs'
import { login, USERS, sql, be, check, results } from './lib.mjs'
const IDS = JSON.parse(readFileSync('C:/Users/Usuario/Desktop/EIE/scratchpad-remitos-compra/ids.json', 'utf8'))
const { accA, br1, alf, client } = IDS
const stock = (pid, br) => Number(sql(`select coalesce(sum(quantity),0) from branch_stock where product_id='${pid}' and branch_id='${br}'`))
const tok = await login(...USERS.owner)
const AUTH = 'C:/Users/Usuario/Desktop/EIE/scratchpad-remitos-compra/qa-auth-owner.json'
const browser = await chromium.launch()
await uiLogin(browser, ...USERS.owner, AUTH)
const ctx = await newCtx(browser, 'desktop', 'light', AUTH)
const page = await ctx.newPage()
const mk = await be(tok, 'POST', '/delivery-notes', { client_id: client, branch_id: br1, items: [{ product_id: alf, quantity: 2, price: 500, subtotal: 1000 }] }, { 'Idempotency-Key': crypto.randomUUID() })
const dn = mk.body.id
const s0 = stock(alf, br1)
const movs0 = Number(sql(`select count(*) from stock_movements where account_id='${accA}'`))
await page.goto(`${BASE}/remitos/${dn}`, { waitUntil: 'domcontentloaded', timeout: 180000 })
await page.getByRole('button', { name: /^Venta$/ }).waitFor({ timeout: 120000 })
await page.getByRole('button', { name: /^Venta$/ }).click()
const d = page.getByRole('dialog')
await d.getByText('Pasar a venta').first().waitFor({ timeout: 60000 })
await page.waitForTimeout(1500)
await page.screenshot({ path: 'C:/Users/Usuario/Desktop/EIE/scratchpad-remitos-compra/capturas/venta-b-dialogo-pasar-a-venta-desktop-light.png' })
// forma de pago del catálogo: la primera disponible
const pm = d.getByRole('combobox').first()
await pm.click()
console.log('OPTIONS', JSON.stringify(await page.getByRole('option').allInnerTexts()))
 await page.getByRole('option', { name: /Otro/ }).first().click()
await page.waitForTimeout(500)
console.log('DLG', (await d.innerText()).split(String.fromCharCode(10)).join(' | ').slice(0,600))
await d.getByRole('button', { name: 'Registrar venta' }).click()
await page.getByText(/Venta registrada/).first().waitFor({ timeout: 60000 })
const st = sql(`select status from delivery_notes where id='${dn}'`)
check('(venta-b) convertir en venta por la UI: remito convertido', st === 'converted', st)
check('(venta-b) la conversión NO vuelve a descontar stock', stock(alf, br1) === s0 && Number(sql(`select count(*) from stock_movements where account_id='${accA}'`)) === movs0, `${s0}->${stock(alf, br1)}`)
const op = sql(`select sale_operation_id from sales_orders where account_id='${accA}' and source_delivery_note_id='${dn}' limit 1`)
check('(venta-b) existe la venta con origen en el remito', !!op, op)
const del = await be(tok, 'DELETE', `/sales?operation_id=${op}`)
check('(venta-b) borrar la venta nacida del remito: 204', del.status === 204, `${del.status} ${JSON.stringify(del.body)}`)
check('(venta-b) el remito vuelve a pendiente y el stock sigue descontado (sin reposición)', sql(`select status from delivery_notes where id='${dn}'`) === 'issued' && stock(alf, br1) === s0, `${sql(`select status from delivery_notes where id='${dn}'`)} stock ${s0}->${stock(alf, br1)}`)
// presupuesto: compartir (DocumentShareMenu es compartido)
const q = await be(tok, 'POST', '/quotes', { client_id: client, valid_until: new Date(Date.now() + 864e6).toISOString().slice(0, 10), items: [{ product_id: alf, quantity: 1, price: 500, subtotal: 500 }] })
check('(venta-b) presupuesto: se crea (201)', q.status === 201, `${q.status}`)
await page.goto(`${BASE}/presupuestos/${q.body.id}`, { waitUntil: 'domcontentloaded', timeout: 180000 })
await page.getByRole('button', { name: 'Compartir' }).waitFor({ timeout: 120000 })
await page.getByRole('button', { name: 'Compartir' }).click()
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 30000 }), page.getByRole('menuitem', { name: 'Descargar PDF' }).click()])
check('(venta-b) presupuesto: se comparte (descarga del PDF)', /presupuesto|P-\d+/i.test(dl.suggestedFilename()), dl.suggestedFilename())
const failed = results.filter(([, ok]) => !ok)
console.log(`RESUMEN venta-b: ${results.length - failed.length}/${results.length} PASS`)
await browser.close()
