-- =======================================================================================
-- MIGRATION: 20260227000100_admin_analytics_v1.sql
-- DESCRIPTION: Core analytics backend for the EIE Admin Dashboard (MVP V1)
-- INCLUDES: RLS, Helper Functions, Analytics Views, and Aggregation RPCs (D3-Friendly)
-- =======================================================================================

-- ---------------------------------------------------------------------------------------
-- A1 & A2: SCHEMA ENHANCEMENTS AND INDICES
-- Note: profiles.role 'admin' | 'user' already exists in 001_create_profiles.sql
-- ---------------------------------------------------------------------------------------

-- Add indices to speed up analytics_events aggregations
CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON public.analytics_events(created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_name_created_at ON public.analytics_events(event_name, created_at);

-- ---------------------------------------------------------------------------------------
-- A3: SECURITY HELPER FUNCTIONS
-- ---------------------------------------------------------------------------------------

-- Helper function to strictly check if a user is an admin
CREATE OR REPLACE FUNCTION public.is_admin(uid uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = uid AND role = 'admin'
  );
$$;

-- Allow users to insert their own analytics events (if missing), and admins to select all
DROP POLICY IF EXISTS "Users can insert own events" ON public.analytics_events;
CREATE POLICY "Users can insert own events" ON public.analytics_events
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can read all events" ON public.analytics_events;
CREATE POLICY "Admins can read all events" ON public.analytics_events
  FOR SELECT USING (public.is_admin(auth.uid()));

-- ---------------------------------------------------------------------------------------
-- A4 & A5: RPCs FOR ADMIN DASHBOARD (D3-FRIENDLY AGGREGATIONS)
-- ---------------------------------------------------------------------------------------

-- RPC 1: OVERVIEW KPIs & SERIES (UMV, Activation, Insights, Community)
CREATE OR REPLACE FUNCTION public.rpc_admin_kpi_overview(
  date_from timestamptz,
  date_to timestamptz,
  granularity text DEFAULT 'day'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result jsonb;
BEGIN
  -- Strict Authorization
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Access denied: Admin only';
  END IF;

  WITH date_series AS (
    SELECT generate_series(
      date_trunc(granularity, date_from),
      date_trunc(granularity, date_to),
      (CASE WHEN granularity = 'week' THEN '1 week'::interval ELSE '1 day'::interval END)
    ) AS period
  ),
  
  -- Activation / Users With First Operation
  -- We rely on the event 'first_operation' generated by Edge Functions
  activations AS (
    SELECT 
      date_trunc(granularity, created_at) AS period,
      COUNT(DISTINCT user_id) as users_count
    FROM analytics_events
    WHERE event_name = 'first_operation'
      AND created_at BETWEEN date_from AND date_to
    GROUP BY 1
  ),
  
  -- UMV / Users Reaching UMV for the first time
  -- UMV Definition: Has performed an operation AND has generated an insight.
  -- We identify the exact timestamp a user achieved both, which is the MAX of their first operation and first insight.
  user_activity AS (
    SELECT 
      user_id,
      MIN(CASE WHEN event_name = 'first_operation' THEN created_at END) as first_op_time,
      MIN(CASE WHEN event_name = 'insight_generated' THEN created_at END) as first_insight_time
    FROM analytics_events
    GROUP BY user_id
  ),
  user_umv AS (
    SELECT 
      user_id,
      GREATEST(first_op_time, first_insight_time) AS umv_achieved_at
    FROM user_activity
    WHERE first_op_time IS NOT NULL AND first_insight_time IS NOT NULL
  ),
  umv_series AS (
    SELECT 
      date_trunc(granularity, umv_achieved_at) AS period,
      COUNT(DISTINCT user_id) AS umv_users_count
    FROM user_umv
    WHERE umv_achieved_at BETWEEN date_from AND date_to
    GROUP BY 1
  ),

  -- Insights Generated
  insights_series AS (
    SELECT 
      date_trunc(granularity, created_at) AS period,
      event_data->>'type' AS insight_type,
      COUNT(*) as count
    FROM analytics_events
    WHERE event_name = 'insight_generated'
      AND created_at BETWEEN date_from AND date_to
    GROUP BY 1, 2
  ),
  
  -- Community Engagement
  community_series AS (
    SELECT 
      date_trunc(granularity, created_at) AS period,
      event_name,
      COUNT(*) as count,
      COUNT(DISTINCT user_id) as active_users
    FROM analytics_events
    WHERE event_name IN ('post_created', 'reply_created')
      AND created_at BETWEEN date_from AND date_to
    GROUP BY 1, 2
  )

  -- Aggregate Everything into JSON
  SELECT jsonb_build_object(
    'time_series', (
      SELECT jsonb_agg(
        jsonb_build_object(
          'period', ds.period,
          'activations', COALESCE(a.users_count, 0),
          'umv_achieved', COALESCE(u.umv_users_count, 0)
        ) ORDER BY ds.period
      )
      FROM date_series ds
      LEFT JOIN activations a ON ds.period = a.period
      LEFT JOIN umv_series u ON ds.period = u.period
    ),
    'insights_breakdown', (
      SELECT COALESCE(jsonb_agg(row_to_json(i)), '[]'::jsonb)
      FROM insights_series i
    ),
    'community_engagement', (
      SELECT COALESCE(jsonb_agg(row_to_json(c)), '[]'::jsonb)
      FROM community_series c
    ),
    'summary', jsonb_build_object(
      'total_activations_in_range', (SELECT COALESCE(SUM(users_count), 0) FROM activations),
      'total_umv_in_range', (SELECT COALESCE(SUM(umv_users_count), 0) FROM umv_series)
    )
  ) INTO result;

  RETURN result;
END;
$$;


-- RPC 2: COHORT RETENTION (30 DAYS)
CREATE OR REPLACE FUNCTION public.rpc_admin_retention_30d(
  cohort_granularity text DEFAULT 'week',
  date_from timestamptz DEFAULT (now() - interval '90 days'),
  date_to timestamptz DEFAULT now()
)
RETURNS TABLE (
  cohort_start timestamptz,
  cohort_size bigint,
  retained_30d bigint,
  retention_rate numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Access denied: Admin only';
  END IF;

  RETURN QUERY
  WITH user_cohorts AS (
    -- Cohort assignment based on First Operation
    SELECT 
      user_id,
      date_trunc(cohort_granularity, created_at) AS cohort_period,
      created_at AS activation_time
    FROM analytics_events
    WHERE event_name = 'first_operation'
      AND created_at BETWEEN date_from AND date_to
  ),
  user_retention AS (
    -- A user is retained if they perform ANY operation between Day 30 and Day 37 after activation
    SELECT DISTINCT
      c.user_id,
      c.cohort_period
    FROM user_cohorts c
    JOIN analytics_events e ON c.user_id = e.user_id
    WHERE e.event_name = 'operation_created'
      AND e.created_at >= c.activation_time + interval '30 days'
      AND e.created_at < c.activation_time + interval '37 days'
  ),
  cohort_sizes AS (
    SELECT cohort_period, COUNT(user_id) AS total_users
    FROM user_cohorts
    GROUP BY cohort_period
  ),
  retained_sizes AS (
    SELECT cohort_period, COUNT(user_id) AS retained_users
    FROM user_retention
    GROUP BY cohort_period
  )
  SELECT 
    cs.cohort_period AS cohort_start,
    cs.total_users AS cohort_size,
    COALESCE(rs.retained_users, 0) AS retained_30d,
    ROUND((COALESCE(rs.retained_users, 0)::numeric / cs.total_users::numeric) * 100, 2) AS retention_rate
  FROM cohort_sizes cs
  LEFT JOIN retained_sizes rs ON cs.cohort_period = rs.cohort_period
  ORDER BY cs.cohort_period;
END;
$$;


-- RPC 3: WEEKLY USAGE DISTRIBUTION (HABIT)
CREATE OR REPLACE FUNCTION public.rpc_admin_weekly_usage_distribution(
  date_from timestamptz,
  date_to timestamptz
)
RETURNS TABLE (
  week_start timestamptz,
  active_days integer,
  users_count bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Access denied: Admin only';
  END IF;

  RETURN QUERY
  WITH user_active_days AS (
    -- Count distinct active days per user per week
    SELECT 
      user_id,
      date_trunc('week', created_at) AS week_period,
      COUNT(DISTINCT date_trunc('day', created_at))::integer AS active_days
    FROM analytics_events
    WHERE event_name = 'operation_created'
      AND created_at BETWEEN date_from AND date_to
    GROUP BY user_id, date_trunc('week', created_at)
  )
  SELECT 
    week_period AS week_start,
    active_days,
    COUNT(user_id) AS users_count
  FROM user_active_days
  GROUP BY week_period, active_days
  ORDER BY week_period, active_days;
END;
$$;
